--- #YAML:1.0
name:               Plack-Middleware-CSS-Compressor
version:            0.01
abstract:           Plack middleware to compress stylesheets
author:
    - Simon Bertrang <janus@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CSS::Compressor:  0
    Plack:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
